Import des données

In [47]:
import pandas as pd
df = pd.read_csv(
 'https://www.data.gouv.fr/fr/datasets/r/182268fc-2103-4bcb-a850-6cf90b02a9eb'
)

/tmp/ipykernel_3200/572529936.py:2: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

Import des fonctions du fichier fonctions.py nécessaires au DM

In [48]:
from fonctions import *

la tete des données ça ressemble à quoi

In [49]:
df.head(5)

,code_departement,libelle_departement,code_commune,libelle_commune,prenom,nom,voix
0,01,Ain,1,L'Abergement-Clémenciat,Nathalie,ARTHAUD,3
1,01,Ain,2,L'Abergement-de-Varey,Nathalie,ARTHAUD,2
2,01,Ain,4,Ambérieu-en-Bugey,Nathalie,ARTHAUD,38
3,01,Ain,5,Ambérieux-en-Dombes,Nathalie,ARTHAUD,8
4,01,Ain,6,Ambléon,Nathalie,ARTHAUD,0

**Question 1**

In [50]:
#vérification du format : pour que "01" reste "01" et ne devienne pas "1"
df["code_departement"] = df["code_departement"].astype(str).str.zfill(2)
df["code_commune"] = df["code_commune"].astype(str).str.zfill(3)

df["code_commune"] = df["code_departement"] + df["code_commune"]

df["candidat"] = df["prenom"].fillna("") + " " + df["nom"].fillna("")

vérification de la manip

In [51]:
df.head(5)

,code_departement,libelle_departement,code_commune,libelle_commune,prenom,nom,voix,candidat
0,01,Ain,01001,L'Abergement-Clémenciat,Nathalie,ARTHAUD,3,Nathalie ARTHAUD
1,01,Ain,01002,L'Abergement-de-Varey,Nathalie,ARTHAUD,2,Nathalie ARTHAUD
2,01,Ain,01004,Ambérieu-en-Bugey,Nathalie,ARTHAUD,38,Nathalie ARTHAUD
3,01,Ain,01005,Ambérieux-en-Dombes,Nathalie,ARTHAUD,8,Nathalie ARTHAUD
4,01,Ain,01006,Ambléon,Nathalie,ARTHAUD,0,Nathalie ARTHAUD

vérifions si on a bien gardé les bulletins abstentions, blancs ou nuls

In [52]:
df["candidat"].str.contains("BLANC|NUL|ABSTENTION", case=False, na=False).any()

np.True_

Question 2

In [53]:
fonctions.compter_candidats(df)

"En 2022, il y avait 12 candidats à l'élection présidentielle."

Question 3

In [65]:
fonctions.scores_nationaux(df)

                 candidat  nombre_vote    score_%
0             abstentions     12824169  26.307134
1         Emmanuel MACRON      9783058  20.068686
2           Marine LE PEN      8133828  16.685502
3      Jean-Luc MÉLENCHON      7712520  15.821243
4            Éric ZEMMOUR      2485226   5.098122
5        Valérie PÉCRESSE      1679001   3.444255
6           Yannick JADOT      1627853   3.339331
7           Jean LASSALLE      1101387   2.259354
8          Fabien ROUSSEL       802422   1.646066
9   Nicolas DUPONT-AIGNAN       725176   1.487605
10           Anne HIDALGO       616478   1.264625
11                 blancs       543609   1.115144
12        Philippe POUTOU       268904   0.551622
13                   nuls       247151   0.506998
14       Nathalie ARTHAUD       197094   0.404313

In [64]:
dir(fonctions)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'compter_candidats',
 'pd',
 'scores_nationaux']

In [63]:
import fonctions
import importlib
importlib.reload(fonctions)