Import des données

In [1]:
import pandas as pd
df = pd.read_csv(
 'https://www.data.gouv.fr/fr/datasets/r/182268fc-2103-4bcb-a850-6cf90b02a9eb'
)

/tmp/ipykernel_3200/572529936.py:2: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

Import des fonctions du fichier fonctions.py nécessaires au DM

In [25]:
from fonctions import *

la tete des données ça ressemble à quoi

In [5]:
df.head(5)

,code_departement,libelle_departement,code_commune,libelle_commune,prenom,nom,voix,candidat
0,01,Ain,01001,L'Abergement-Clémenciat,Nathalie,ARTHAUD,3,Nathalie ARTHAUD
1,01,Ain,01002,L'Abergement-de-Varey,Nathalie,ARTHAUD,2,Nathalie ARTHAUD
2,01,Ain,01004,Ambérieu-en-Bugey,Nathalie,ARTHAUD,38,Nathalie ARTHAUD
3,01,Ain,01005,Ambérieux-en-Dombes,Nathalie,ARTHAUD,8,Nathalie ARTHAUD
4,01,Ain,01006,Ambléon,Nathalie,ARTHAUD,0,Nathalie ARTHAUD

**Question 1**

In [10]:
#vérification du format : pour que "01" reste "01" et ne devienne pas "1"
df["code_departement"] = df["code_departement"].astype(str).str.zfill(2)
df["code_commune"] = df["code_commune"].astype(str).str.zfill(3)

df["code_commune"] = df["code_departement"] + df["code_commune"]

df["candidat"] = df["prenom"].fillna("") + " " + df["nom"].fillna("")

vérification de la manip

In [11]:
df.head(5)

,code_departement,libelle_departement,code_commune,libelle_commune,prenom,nom,voix,candidat
0,01,Ain,0101001,L'Abergement-Clémenciat,Nathalie,ARTHAUD,3,Nathalie ARTHAUD
1,01,Ain,0101002,L'Abergement-de-Varey,Nathalie,ARTHAUD,2,Nathalie ARTHAUD
2,01,Ain,0101004,Ambérieu-en-Bugey,Nathalie,ARTHAUD,38,Nathalie ARTHAUD
3,01,Ain,0101005,Ambérieux-en-Dombes,Nathalie,ARTHAUD,8,Nathalie ARTHAUD
4,01,Ain,0101006,Ambléon,Nathalie,ARTHAUD,0,Nathalie ARTHAUD

vérifions si on a bien gardé les bulletins abstentions, blancs ou nuls

In [ ]:
df["candidat"].str.contains("BLANC|NUL|ABSTENTION", case=False, na=False).any()

Empty DataFrame
Columns: [code_departement, libelle_departement, code_commune, libelle_commune, prenom, nom, voix, candidat]
Index: []

Question 2

In [29]:
fonctions.compter_candidats(df)

"En 2022, il y avait 12 candidats à l'élection présidentielle."